language: cpp

perl:
  - "5.28"

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
  - sudo apt-get update
  - echo Requirements for InfoParse
  - sudo apt-get install cmake make libboost-all-dev doxygen
  - sudo apt-get install perl
  - sudo python -m pip install --upgrade pip
  - sudo python -m pip install conan mkdocs --ignore-installed
  - echo Requirements for GCC 9.1
#  - sudo bash mkGCC.sh
  - eval "${MATRIX_EVAL}"
  - export PATH="$PATH:/home/travis/.local/bin"

install:
  - mkdir build && cd build
  - conan install .. --build missing

script:
  - cmake ..
  - make
  - cd test
  - ctest -V

after_success:
  - doxygen .doxygen
  - perl ./mkdox.pl
  - mkdocs build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  file: "docs"
  on:
    branch: master

notifications:
  email: false

