language: cpp

perl:
  - "5.28"

before_install:
  - sudo apt-get update
  - sudo apt-get install cmake make gcc libboost-all-dev doxygen
  - sudo apt-get install perl
  - sudo python -m pip install --upgrade pip
  - sudo python -m pip install --user conan mkdocs

install:
  - mkdir build && cd build
  - python -m conan install .. --build missing

script:
  - cmake .. -G "UNIX Makefiles"
  - cmake --build .
  - ctest

after_success:
  - doxygen .doxygen
  - perl ./mkdox.pl
  - python -m mkdocs build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master

notifications:
  email: false

