site_name: InfoParse

site_dir: infoparse

docs_dir: dox_site

nav:
  - Home:
      - Home: index.md
      - Installation: installation.md
  - Docs:
      - API: api.md
      - Parsing rules: parsing.md
  - Source:
      - Conventions: convention.md
      - 'Build it yourself': build.md
  - Doxygen: doxygen/index.html
