site_name: InfoParse

site_dir: infoparse

docs_dir: dox_site

nav:
  - Home:
      - Home: index.md
      - Installation: installation.md
      - 'Build it yourself': build.md
  - Source:
      - Conventions: convention.md
  - Doxygen: doxygen/index.html
