string(TIMESTAMP INFO_PARSE_BUILD_DATE "%Y-%m-%d %H:%M:%S (%s)" UTC)

set(INFO_PARSE_CLASSIC_VERSION_MAJOR 2)
set(INFO_PARSE_CLASSIC_VERSION_MINOR 0)
set(INFO_PARSE_CLASSIC_VERSION_PATCH 1)
set(INFO_PARSE_CLASSIC_VERSION "${INFO_PARSE_CLASSIC_VERSION_MAJOR}.${INFO_PARSE_CLASSIC_VERSION_MINOR}.${INFO_PARSE_CLASSIC_VERSION_PATCH}")

set(INFO_PARSE_NEO_VERSION_MAJOR 0)
set(INFO_PARSE_NEO_VERSION_MINOR 1)
set(INFO_PARSE_NEO_VERSION_PATCH 0)
set(INFO_PARSE_NEO_VERSION "${INFO_PARSE_NEO_VERSION_MAJOR}.${INFO_PARSE_NEO_VERSION_MINOR}.${INFO_PARSE_NEO_VERSION_PATCH}")

set(INFO_PARSE_SOURCE_DIR "${CMAKE_SOURCE_DIR}/src")
set(INFO_PARSE_INCLUDE_DIR "${CMAKE_SOURCE_DIR}/include/info/parse")
set(INFO_PARSE_CONFIG_DIR "${CMAKE_SOURCE_DIR}/config")
set(INFO_PARSE_TESTS_DIR "${CMAKE_SOURCE_DIR}/test")
